### ISSUE TITLE
Old WorldGuard bypass mode?

### ISSUE THREAD

**Issue by eris-webserv** [JorianWoltjer/LiveOverflowMod#1]
The old WorldGuard bypass mode could be used for a bit more stuff. Can it be added?

**Comment by JorianWoltjer** [comment]
It's definitely a good idea to include this mode. I'll try and see how I can fit it in easily, but the code itself should be pretty simple

**Comment by JorianWoltjer** [comment]
I had some time, so I implemented it right away. I thought a logical way would be to:

* Use the **slow** bypass when walking
* Use the **fast** bypass when sprinting

With the built-in toggle sprint it acts almost like a simple toggle. And it should not affect the normal sprint function as all movement is disabled when the WorldGuard Bypass is active. 

Here's the commit that solves this issue: https://github.com/JorianWoltjer/LiveOverflowMod/commit/a42a9e04d9d9fffae71cbabe67c363e39673ce7c

**Comment by eris-webserv** [comment]
I like the implementation! Thanks :)
