### ISSUE TITLE
[FR] Flight

### ISSUE THREAD

**Issue by eris-webserv** [JorianWoltjer/LiveOverflowMod#2]
In one of LiveOverflow's videos, he outlined a way to bypass the Minecraft flight check- something even most public hack clients have issues with.
Maybe add the flight system he outlined? Would be very useful, considering I don't enjoy being kicked every 7 seconds for being in the fucking sky.

**Comment by JorianWoltjer** [comment]
That would be something nice to add for the WorldGuard Bypass. For normal flight I just use Meteor Client, but I'll have a look and see how easy it would be to implement a flight check bypass for it

**Comment by eris-webserv** [comment]
> That would be something nice to add for the WorldGuard Bypass. For normal flight I just use Meteor Client, but I'll have a look and see how easy it would be to implement a flight check bypass for it

Just make it a different hack. The Worldguard bypass is starting to become more like the sculk sensor- too much loaded on it.

**Comment by JorianWoltjer** [comment]
Thanks for the idea. I took some time to implement it into the mod and have it somewhat working. It basically sends a small downwards movement every 1.5 seconds, to reset the flight timer. 

While working on this I realized it's not as easy as I thought, so on a server with medium/high ping it might fail. If anyone can implement a better way feel free to submit a Pull Request. 

Here's the commit that fixes this issue: https://github.com/JorianWoltjer/LiveOverflowMod/commit/cd4c4c2b47964c95ca295eea4d7e9fa0d9d70238

**Comment by eris-webserv** [comment]
Didn't LiveOverflow send a spoofed downwards packet to eliminate that annoyance?
Also, as I said, the poor Worldguard bypass is starting to get too bloated- maybe make the Flight hack a different hack?

**Comment by JorianWoltjer** [comment]
Whatever I try doesn't really want to work together with the WorldGuard Bypass. I have already implemented it in a similar way to LiveOverflow, as I am sending a packet with the position down. It seems to work decently if you're not going straight up, so I think I'll keep it this way as I don't know a better way. 

As for a separate hack, I don't want to have too many keybinds for different hacks, and don't need a specific Flight hack myself. So I would rather add this little piece of code to the WorldGuard Bypass than to add a whole new hack for just the anti-fly kick that you would only use together with WorldGuard. The code is quite commented so it should still be understandable. 

And remember, if you want to try/add something yourself you can always fork it and edit the source code

**Comment by eris-webserv** [comment]
Alright, fair enough. The only reason I'm suggesting all this is because I barely know how to print hello world in java :(
